services:
  postgres:
    image: postgres:16-alpine
    container_name: ticketflash_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ticketflash-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ticketflash_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - ticketflash-network
    restart: unless-stopped
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    container_name: ticketflash_redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - ticketflash-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: ticketflash_rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  ticketflash-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  rabbitmq_data:
    driver: local
