spring.application.name=TicketFlash
spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=dev

app.jwt.secret=${JWT_SECRET_KEY}
app.jwt.expiration=${JWT_EXPIRATION_TIME}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.repositories.enabled=false

#Defalut là 60s, giảm còm 100ms để fail-fast
spring.data.redis.timeout= 100ms
# Số lượng kết nối tối đa mở cùng lúc tới Redis
spring.data.redis.lettuce.pool.max-active=100
spring.data.redis.lettuce.pool.max-idle=20
spring.data.redis.lettuce.pool.min-idle=5
# Nếu hồ chứa cạn, request mới chỉ được đứng chờ tối đa 50ms để mượn kết nối.
spring.data.redis.lettuce.pool.max-wait=50ms